CATEGORIES_DICTIONARY = {
    "0X10K Club": "0x10k-club",
    "0X99 Club": "0x99-club",
    "0X999 Club": "0x999-club",
    "0Xemojis": "0xemojis",
    "1 Hex Club": "1-hex-club",
    "1 Letter": "1-letter",
    "100K Club": "100k-club",
    "10K Club": "10k-club",
    "2 Char Ln Nl": "2-char-ln-nl",
    "2 Digit Palindromes": "2-digit-palindromes",
    "2 Hex Club": "2-hex-club",
    "2 Letter Palindromes": "2-letter-palindromes",
    "2 Letters": "2-letters",
    "24 Clock Times": "24-Clock-Times",
    "24H Club": "24h-club",
    "3 Digit Palindromes": "3-digit-palindromes",
    "3 Hex Club": "3-hex-club",
    "3 Letter All Vowels": "3-letter-all-vowels",
    "3 Letter Dictionary": "3-letter-dictionary",
    "3 Letter First Names": "3-letter-first-names",
    "3 Letter Palindromes": "3-letter-palindromes",
    "3 Letters": "3-letters",
    "365 Club": "365-club",
    "3L Months": "3l-months",
    "4 Digit Palindromes": "4-digit-palindromes",
    "4 Letter Dictionary": "4-letter-dictionary",
    "5 Digit James Bond": "5-digit-james-bond",
    "5 Digit Palindromes": "5-digit-palindromes",
    "5 Letter Dictionary": "5-letter-dictionary",
    "6 Digit Palindromes": "6-digit-palindromes",
    "9 Club": "9-club",
    "99 Club": "99-club",
    "999 Club": "999-club",
    "999 Club Sns Chinese": "999-club-sns-chinese",
    "999 Cn Capitalized Club": "999-cn-capitalized-club",
    "999 Cn Club": "999-cn-club",
    "999 Japan Official": "999-japan-official",
    "999Th Club": "999th-club",
    "Aus 999 Club": "aus-999-club",
    "Binary Club": "binary-club",
    "Capital Cities": "capital-cities",
    "Cn 10K Club": "cn-10k-club",
    "Countries": "countries",
    "Country Codes": "country-codes",
    "Country Leaders": "country-leaders",
    "Dbz Characters": "dbz-characters",
    "Double Emoji": "double-emoji",
    "Double Hyphens Lv Lv": "double-hyphens-lv-lv",
    "Double Hyphens Vv Vv": "double-hyphens-vv-vv",
    "Emoji Flag Club": "emoji-flag-club",
    "Emoji Quads": "emoji-quads",
    "English Adjectives": "english-adjectives",
    "English Nouns": "english-nouns",
    "English Verbs": "english-verbs",
    "Female Firstnames": "female-firstnames",
    "Flagcountry Club": "flagcountry-club",
    "Gen1 Pokemon": "gen1-pokemon",
    "Gold People Emojis": "gold-people-emojis",
    "Got Houses Club": "got-houses-club",
    "Harry Potter": "harry-potter",
    "Hyphens Ll": "hyphens-ll",
    "Hyphens Ln Nl": "hyphens-ln-nl",
    "Hyphens Nn": "hyphens-nn",
    "Hyphens Nnn": "hyphens-nnn",
    "Jurassic Sns": "jurassic-sns",
    "Kanye Sns Club": "kanye-sns-club",
    "Languages Of The World": "languages-of-the-world",
    "Male Firstnames": "male-firstnames",
    "Marvel Club": "marvel-club",
    "Mmdd Club": "mmdd-club",
    "Mnemonic Club": "mnemonic-club",
    "Months": "months",
    "Naruto Names": "naruto-names",
    "Nasdaq Sns Index": "Nasdaq-sns-index",
    "Negative 999 Club": "negative-999-club",
    "Palindrome Cities": "palindrome-cities",
    "Pokemon Trainer Dao": "pokemon-trainer-dao",
    "Psalms Club": "psalms-club",
    "Roman Numerals 969 Club": "Roman-Numerals-969-Club",
    "Single Digit Multiplication": "Single-Digit-Multiplication",
    "Single Emoji": "single-emoji",
    "Skateboard Tricks": "skateboard-tricks",
    "Sns Date Club": "sns-date-club",
    "Sns Full Date Club": "sns-full-date-club",
    "Spanish Nouns": "spanish-nouns",
    "Spanish Verbs": "spanish-verbs",
    "Strobogrammatic Club": "strobogrammatic-club",
    "Substances Club": "substances-club",
    "Surnames": "surnames",
    "The Cents Club": "the-cents-club",
    "Tolkien": "tolkien",
    "Traditional Cn 999 Club": "traditional-cn-999-club",
    "Triple Emoji": "triple-emoji",
    "Us 999 Club": "us-999-club",
}

CATEGORIES_DICTIONARY_INVERTED = {
    "0x10k-club": "0X10K Club",
    "0x99-club": "0X99 Club",
    "0x999-club": "0X999 Club",
    "0xemojis": "0Xemojis",
    "1-hex-club": "1 Hex Club",
    "1-letter": "1 Letter",
    "100k-club": "100K Club",
    "10k-club": "10K Club",
    "2-char-ln-nl": "2 Char Ln Nl",
    "2-digit-palindromes": "2 Digit Palindromes",
    "2-hex-club": "2 Hex Club",
    "2-letter-palindromes": "2 Letter Palindromes",
    "2-letters": "2 Letters",
    "24-Clock-Times": "24 Clock Times",
    "24h-club": "24H Club",
    "3-digit-palindromes": "3 Digit Palindromes",
    "3-hex-club": "3 Hex Club",
    "3-letter-all-vowels": "3 Letter All Vowels",
    "3-letter-dictionary": "3 Letter Dictionary",
    "3-letter-first-names": "3 Letter First Names",
    "3-letter-palindromes": "3 Letter Palindromes",
    "3-letters": "3 Letters",
    "365-club": "365 Club",
    "3l-months": "3L Months",
    "4-digit-palindromes": "4 Digit Palindromes",
    "4-letter-dictionary": "4 Letter Dictionary",
    "5-digit-james-bond": "5 Digit James Bond",
    "5-digit-palindromes": "5 Digit Palindromes",
    "5-letter-dictionary": "5 Letter Dictionary",
    "6-digit-palindromes": "6 Digit Palindromes",
    "9-club": "9 Club",
    "99-club": "99 Club",
    "999-club": "999 Club",
    "999-club-sns-chinese": "999 Club Sns Chinese",
    "999-cn-capitalized-club": "999 Cn Capitalized Club",
    "999-cn-club": "999 Cn Club",
    "999-japan-official": "999 Japan Official",
    "999th-club": "999Th Club",
    "aus-999-club": "Aus 999 Club",
    "binary-club": "Binary Club",
    "capital-cities": "Capital Cities",
    "cn-10k-club": "Cn 10K Club",
    "countries": "Countries",
    "country-codes": "Country Codes",
    "country-leaders": "Country Leaders",
    "dbz-characters": "Dbz Characters",
    "double-emoji": "Double Emoji",
    "double-hyphens-lv-lv": "Double Hyphens Lv Lv",
    "double-hyphens-vv-vv": "Double Hyphens Vv Vv",
    "emoji-flag-club": "Emoji Flag Club",
    "emoji-quads": "Emoji Quads",
    "english-adjectives": "English Adjectives",
    "english-nouns": "English Nouns",
    "english-verbs": "English Verbs",
    "female-firstnames": "Female Firstnames",
    "flagcountry-club": "Flagcountry Club",
    "gen1-pokemon": "Gen1 Pokemon",
    "gold-people-emojis": "Gold People Emojis",
    "got-houses-club": "Got Houses Club",
    "harry-potter": "Harry Potter",
    "hyphens-ll": "Hyphens Ll",
    "hyphens-ln-nl": "Hyphens Ln Nl",
    "hyphens-nn": "Hyphens Nn",
    "hyphens-nnn": "Hyphens Nnn",
    "jurassic-sns": "Jurassic Sns",
    "kanye-sns-club": "Kanye Sns Club",
    "languages-of-the-world": "Languages Of The World",
    "male-firstnames": "Male Firstnames",
    "marvel-club": "Marvel Club",
    "mmdd-club": "Mmdd Club",
    "mnemonic-club": "Mnemonic Club",
    "months": "Months",
    "naruto-names": "Naruto Names",
    "Nasdaq-sns-index": "Nasdaq Sns Index",
    "negative-999-club": "Negative 999 Club",
    "palindrome-cities": "Palindrome Cities",
    "pokemon-trainer-dao": "Pokemon Trainer Dao",
    "psalms-club": "Psalms Club",
    "Roman-Numerals-969-Club": "Roman Numerals 969 Club",
    "Single-Digit-Multiplication": "Single Digit Multiplication",
    "single-emoji": "Single Emoji",
    "skateboard-tricks": "Skateboard Tricks",
    "sns-date-club": "Sns Date Club",
    "sns-full-date-club": "Sns Full Date Club",
    "spanish-nouns": "Spanish Nouns",
    "spanish-verbs": "Spanish Verbs",
    "strobogrammatic-club": "Strobogrammatic Club",
    "substances-club": "Substances Club",
    "surnames": "Surnames",
    "the-cents-club": "The Cents Club",
    "tolkien": "Tolkien",
    "traditional-cn-999-club": "Traditional Cn 999 Club",
    "triple-emoji": "Triple Emoji",
    "us-999-club": "Us 999 Club",
}
