CATEGORIES_DICTIONARY = {
    "0X10K Club": "0x10k-club",
    "0X99 Club": "0x99-club",
    "0X999 Club": "0x999-club",
    "0Xemojis": "0xemojis",
    "1 Hex Club": "1-hex-club",
    "1 Letter": "1-letter",
    "100K Club": "100k-club",
    "10K Club": "10k-club",
    "2 Char Ln Nl": "2-char-ln-nl",
    "2 Digit Palindromes": "2-digit-palindromes",
    "2 Hex Club": "2-hex-club",
    "2 Letter Palindromes": "2-letter-palindromes",
    "2 Letters": "2-letters",
    "24 Clock Times": "24-Clock-Times",
    "24H Club": "24h-club",
    "3 Digit Palindromes": "3-digit-palindromes",
    "3 Hex Club": "3-hex-club",
    "3 Letter All Vowels": "3-letter-all-vowels",
    "3 Letter Dictionary": "3-letter-dictionary",
    "3 Letter First Names": "3-letter-first-names",
    "3 Letter Palindromes": "3-letter-palindromes",
    "3 Letters": "3-letters",
    "365 Club": "365-club",
    "3L Months": "3l-months",
    "4 Digit Palindromes": "4-digit-palindromes",
    "4 Letter Dictionary": "4-letter-dictionary",
    "5 Digit James Bond": "5-digit-james-bond",
    "5 Digit Palindromes": "5-digit-palindromes",
    "5 Letter Dictionary": "5-letter-dictionary",
    "6 Digit Palindromes": "6-digit-palindromes",
    "9 Club": "9-club",
    "99 Club": "99-club",
    "999 Club": "999-club",
    "999 Club Sns Chinese": "999-club-sns-chinese",
    "999 Cn Capitalized Club": "999-cn-capitalized-club",
    "999 Cn Club": "999-cn-club",
    "999 Japan Official": "999-japan-official",
    "999Th Club": "999th-club",
    "Aus 999 Club": "aus-999-club",
    "Binary Club": "binary-club",
    "Capital Cities": "capital-cities",
    "Cn 10K Club": "cn-10k-club",
    "Countries": "countries",
    "Country Codes": "country-codes",
    "Country Leaders": "country-leaders",
    "Dbz Characters": "dbz-characters",
    "Double Emoji": "double-emoji",
    "Double Hyphens Lv Lv": "double-hyphens-lv-lv",
    "Double Hyphens Vv Vv": "double-hyphens-vv-vv",
    "Emoji Flag Club": "emoji-flag-club",
    "Emoji Quads": "emoji-quads",
    "English Adjectives": "english-adjectives",
    "English Nouns": "english-nouns",
    "English Verbs": "english-verbs",
    "Female Firstnames": "female-firstnames",
    "Flagcountry Club": "flagcountry-club",
    "Gen1 Pokemon": "gen1-pokemon",
    "Gold People Emojis": "gold-people-emojis",
    "Got Houses Club": "got-houses-club",
    "Harry Potter": "harry-potter",
    "Hyphens Ll": "hyphens-ll",
    "Hyphens Ln Nl": "hyphens-ln-nl",
    "Hyphens Nn": "hyphens-nn",
    "Hyphens Nnn": "hyphens-nnn",
    "Jurassic Sns": "jurassic-sns",
    "Kanye Sns Club": "kanye-sns-club",
    "Languages Of The World": "languages-of-the-world",
    "Male Firstnames": "male-firstnames",
    "Marvel Club": "marvel-club",
    "Mmdd Club": "mmdd-club",
    "Mnemonic Club": "mnemonic-club",
    "Months": "months",
    "Naruto Names": "naruto-names",
    "Nasdaq Sns Index": "Nasdaq-sns-index",
    "Negative 999 Club": "negative-999-club",
    "Palindrome Cities": "palindrome-cities",
    "Pokemon Trainer Dao": "pokemon-trainer-dao",
    "Psalms Club": "psalms-club",
    "Roman Numerals 969 Club": "Roman-Numerals-969-Club",
    "Single Digit Multiplication": "Single-Digit-Multiplication",
    "Single Emoji": "single-emoji",
    "Skateboard Tricks": "skateboard-tricks",
    "Sns Date Club": "sns-date-club",
    "Sns Full Date Club": "sns-full-date-club",
    "Spanish Nouns": "spanish-nouns",
    "Spanish Verbs": "spanish-verbs",
    "Strobogrammatic Club": "strobogrammatic-club",
    "Substances Club": "substances-club",
    "Surnames": "surnames",
    "The Cents Club": "the-cents-club",
    "Tolkien": "tolkien",
    "Traditional Cn 999 Club": "traditional-cn-999-club",
    "Triple Emoji": "triple-emoji",
    "Us 999 Club": "us-999-club",
}
